### ISSUE TITLE
I am getting an error while running this code

### ISSUE THREAD

**Issue by mady143** [neoighodaro/pusher-python-realtime-dashboard#1]
Hi @neoighodaro  Iam getting an error while running your code 

ValueError: Invalid app id

**Traceback (most recent call last):
  File "app.py", line 5, in <module>
    pusher = Pusher(app_id=u'PUSHER_APP_ID', key=u'PUSHER_APP_KEY', secret=u'PUSHER_APP_SECRET', cluster=u'PUSHER_APP_CLUSTER')
  File "/home/itm-it1018/anaconda3/lib/python3.6/site-packages/pusher/pusher.py", line 52, in __init__
    json_encoder, json_decoder, backend, **backend_options)
  File "/home/itm-it1018/anaconda3/lib/python3.6/site-packages/pusher/pusher_client.py", line 34, in __init__
    json_encoder, json_decoder, backend, **backend_options)
  File "/home/itm-it1018/anaconda3/lib/python3.6/site-packages/pusher/client.py", line 25, in __init__
    raise ValueError("Invalid app id")
ValueError: Invalid app id**

can you get me the correct answer for this error 

thanks in advance.......

happy codding.......

**Comment by PaulConyngham** [comment]
[you have to signup for a pusher account](https://dashboard.pusher.com/accounts/sign_up) and copy in the your account details into the app.py code

as per the blog instructions for this git here:

https://pusher.com/tutorials/live-dashboard-python#setting-up-pusher

**Comment by mmusunur** [comment]
Thanks @PaulConyngham
